### ISSUE TITLE
Microservice seems to fail with 1.1

### ISSUE THREAD

**Issue by anonymosh** [SoftwareAG/cumulocity-dynamic-mqtt-mapper#20]
Hi all,

I tried to setup the Mapping Service on a new Tenant and while the setup looked ok, it failed on every operation. The log gives the following error:

```
External ID MQTT_MAPPING_SERVICE not found
2022-10-26 11:11:36.719  WARN 13 --- [scheduling-1] c.c.m.context.ContextServiceImpl         : execution of task failed within tenant : t734704630 - null 
2022-10-26 11:11:36.719 ERROR 13 --- [scheduling-1] c.m.s.s.MicroserviceSubscriptionsService : null

java.lang.NullPointerException: null
	at mqtt.mapping.core.C8yAgent.lambda$initialize$1(C8yAgent.java:114)
	at com.cumulocity.microservice.subscription.service.impl.MicroserviceSubscriptionsServiceImpl.lambda$runForTenant$7(MicroserviceSubscriptionsServiceImpl.java:242)
	at com.cumulocity.microservice.context.ContextServiceImpl.callWithinContext(ContextServiceImpl.java:78)
	at com.cumulocity.microservice.subscription.service.impl.MicroserviceSubscriptionsServiceImpl.lambda$callForTenant$8(MicroserviceSubscriptionsServiceImpl.java:251)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.cumulocity.microservice.subscription.service.impl.MicroserviceSubscriptionsServiceImpl.callForTenant(MicroserviceSubscriptionsServiceImpl.java:251)
	at com.cumulocity.microservice.subscription.service.impl.MicroserviceSubscriptionsServiceImpl.runForTenant(MicroserviceSubscriptionsServiceImpl.java:241)
```

I checked that this is a regression on 1.1 by removing the 1.1. MS and installing 1.0 on the same tenant. This gives the message
`2022-10-26 11:40:32.586  INFO 13 --- [main] mqtt.mapping.core.C8yAgent               : Agent has been created with ID ID [type=com_cumulocity_model_idtype_GId, value=131847730]`

After that I was able to update from 1.0 to 1.1 by uploading the new package. So it looks like the new version is not creating the ManagedObject on setup?

Mario

**Comment by sagIoTPower** [comment]
Hi Mario,

can you test again with the latest release v1.2, where the issue should be fixed.

Christof
