### ISSUE TITLE
Error when pulishing payload to mapping in snoop mode

### ISSUE THREAD

**Issue by sagIoTPower** [SoftwareAG/cumulocity-dynamic-mqtt-mapper#43]
When publishing a test payload to the mapping `binaryEvent/berlin_01` an exception occurs: 
```
2023-07-30 11:27:44.340  INFO 11 --- [pool-2-thread-6] m.m.p.inbound.AsynchronousDispatcher     : New message on topic: 'binaryEvent/berlin_01', wrapped message: {"message":"57652077696c6c20616c77617973206170707265636961746520746865206e6578742072656c656173652031302e313721"}
2023-07-30 11:27:44.340  INFO 11 --- [pool-2-thread-6] m.m.processor.inbound.JSONProcessor      : Patched payload: {
  "message" : "57652077696c6c20616c77617973206170707265636961746520746865206e6578742072656c656173652031302e313721",
  "_TOPIC_LEVEL_" : [ "binaryEvent", "berlin_01" ]
}
2023-07-30 11:27:44.342 ERROR 11 --- [pool-2-thread-6] m.m.processor.inbound.JSONProcessor      : Exception for: "Temp: "&$parseInteger($string("0x"&$substring(message,0,2)),"0")&" C", {
  "message" : "57652077696c6c20616c77617973206170707265636961746520746865206e6578742072656c656173652031302e313721",
  "_TOPIC_LEVEL_" : [ "binaryEvent", "berlin_01" ]
}

com.api.jsonata4java.expressions.EvaluateException: Unknown function: $parseInteger
	at com.api.jsonata4java.expressions.Expressions.evaluate(Expressions.java:160)
	at mqtt.mapping.processor.inbound.JSONProcessor.extractFromSource(JSONProcessor.java:99)
	at mqtt.mapping.processor.inbound.AsynchronousDispatcher$MappingProcessor.lambda$call$1(AsynchronousDispatcher.java:149)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at mqtt.mapping.processor.inbound.AsynchronousDispatcher$MappingProcessor.call(AsynchronousDispatcher.java:91)
	at mqtt.mapping.processor.inbound.AsynchronousDispatcher$MappingProcessor.call(AsynchronousDispatcher.java:61)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sagIoTPower** [comment]
Wrong content posted!
